name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Source code checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Check
        run: cargo check
        working-directory: src/lib/wtd-rust
      - name: Test
        run: cargo test --all-targets
        working-directory: src/lib/wtd-rust
      - name: Format
        run: cargo fmt --all -- --check
        working-directory: src/lib/wtd-rust
      - name: Clippy
        run: cargo clippy --all -- -D warnings
        working-directory: src/lib/wtd-rust
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Source code checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
      - name: Build
        run: npm run build