name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source code checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: 0.13.0
          use-tool-cache: true
      - name: Check
        run: cargo check
        working-directory: src/lib/wtd-rust
      - name: Test
        run: cargo test --all-targets
        working-directory: src/lib/wtd-rust
      - name: Format
        run: cargo fmt --all -- --check
        working-directory: src/lib/wtd-rust
      - name: Clippy
        run: cargo clippy --all -- -D warnings
        working-directory: src/lib/wtd-rust
      - name: WASM build
        run: wasm-pack build --target web
        working-directory: src/lib/wtd-rust
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test -- --watch=false --browsers=ChromeHeadless
      - name: Build
        run: npm run build